### ISSUE TITLE
Less file parsing affected by Query String parameters for initially requesting page

### ISSUE THREAD

**Issue by reddogaw** [scott-xu/System.Web.Optimization.Less#17]
When the requesting page includes certain values on the query string, the LESS file parsing fails. In my environment's case, for whatever reason having "id=3033_9589" on the querystring caused: 

```
directive block with unrecognised format on line 3 in file '~/styles/vma-banner.less':
  [2]: @epslanguage: en-AU;
  [3]: @id: 3033_9589;
       ^
  [4]: @import "vma-variables.less";
```

Turns out the answer was to add the setting: **disableParameters="true"** to my web.config dotless section definition.

Suggested solution is to add to LessTransform.cs (line 79):

```
            lessConfig.DisableParameters = true;
```

To explicitly disable querystring usage in bundle generation (since the context of the request is only going to be the pre-cached page's request context (not the bundle's).

**Comment by Gapotchenko** [comment]
We have the same issue. The key for reproduction is to specify a long enough value in parameter, also note the underscore character which triggers the issue.

The parameter below always reproduces the issue for every dotless-enabled website on a first request after web application restart:

<your_url>?a=ZKyOH4NZohcpxfsjkSNdJAYMo5dV8LUqx9MQmEpV06JIaqOnJHhOMGBi_QAGHD

**Comment by ajbeaven** [comment]
I think I may still be hitting this and am unsure if this has been addressed yet. It looks like some related issues have had some recent activity.

I'm getting two exceptions each time I load my site for the first time. When I load the site again, everything functions normally; the css is built correctly with no exceptions.

I'm running dotless 1.5.1 and System.Web.Optimization.Less 1.3.3.

The stack traces for both exceptions are below:

```
System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at dotless.Core.Parser.Tokenizer.GetRegex(String pattern, RegexOptions options)
   at dotless.Core.Parser.Tokenizer.SetupInput(String input, String fileName)
   at dotless.Core.Parser.Tree.Selector.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRules(Env env)
   at dotless.Core.Parser.Tree.Ruleset.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Utils.NodeHelper.ExpandNodes[TNode](Env env, NodeList rules)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRules(Env env)
   at dotless.Core.Parser.Tree.Root.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Root.AppendCSS(Env env)
   at dotless.Core.Parser.Infrastructure.Output.Append(Node node)
   at dotless.Core.Parser.Infrastructure.Nodes.Node.ToCSS(Env env)
   at dotless.Core.LessEngine.TransformToCss(String source, String fileName)
   at dotless.Core.ParameterDecorator.TransformToCss(String source, String fileName)
   at System.Web.Optimization.LessTransform.Process(IEnumerable`1& files) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\LessTransform.cs:line 105
   at System.Web.Optimization.DependencyCache.<>c__DisplayClassa.<GetFileDependencies>b__4(String s) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:line 73
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Web.Optimization.DependencyCache.GetFileDependencies(Bundle bundle, String virtualPath, BundleContext context) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:line 84
   at System.Web.Optimization.DependencyCache.<>c__DisplayClass1.<GetTransientBundleFilesKey>b__0(BundleFile file) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:line 29
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__81`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Web.Optimization.DependencyCache.ComposeTransientFilesKey(IEnumerable`1 paths) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:line 112
   at System.Web.Optimization.DynamicBundle.GetCacheKey(BundleContext context) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DynamicBundle.cs:line 51
   at System.Web.Optimization.HttpContextCache.Get(BundleContext context, Bundle bundle)
   at System.Web.Optimization.Bundle.CacheLookup(BundleContext context)
   at System.Web.Optimization.Bundle.GetBundleResponse(BundleContext context)
   at System.Web.Optimization.BundleResolver.GetBundleContents(String virtualPath)
   at System.Web.Optimization.AssetManager.EliminateDuplicatesAndResolveUrls(IEnumerable`1 refs)
   at System.Web.Optimization.AssetManager.DeterminePathsToRender(IEnumerable`1 assets)
   at System.Web.Optimization.AssetManager.RenderExplicit(String tagFormat, String[] paths)
   at ASP._Page_Views_Shared___Master_cshtml.Execute() in c:\FtpRoot\www.mywebsite.com\Staging\Views\Shared\__Master.cshtml:line 30
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
   at System.Web.WebPages.WebPageBase.PopContext()
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at dotless.Core.Parser.Tokenizer.Chunk.Append(String str) in c:\Users\daniel\Documents\open-source\pandora-container\src\Pandora\Lifestyles\TransientLifestyle.cs:line 0
   at dotless.Core.Parser.Tokenizer.SetupInput(String input, String fileName)
   at dotless.Core.Parser.Tree.Selector.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRules(Env env)
   at dotless.Core.Parser.Tree.Ruleset.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRulesForFrame(Ruleset frame, Env context)
   at dotless.Core.Parser.Tree.MixinDefinition.Evaluate(List`1 args, Env env)
   at dotless.Core.Parser.Tree.MixinCall.Evaluate(Env env)
   at dotless.Core.Utils.NodeHelper.ExpandNodes[TNode](Env env, NodeList rules)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRules(Env env)
   at dotless.Core.Parser.Tree.Ruleset.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Media.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Ruleset.EvaluateRules(Env env)
   at dotless.Core.Parser.Tree.Root.Evaluate(Env env)
   at dotless.Core.Parser.Tree.Root.AppendCSS(Env env)
   at dotless.Core.Parser.Infrastructure.Output.Append(Node node)
   at dotless.Core.Parser.Infrastructure.Nodes.Node.ToCSS(Env env)
   at dotless.Core.LessEngine.TransformToCss(String source, String fileName)
   at dotless.Core.ParameterDecorator.TransformToCss(String source, String fileName)
   at System.Web.Optimization.LessTransform.Process(IEnumerable`1& files) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\LessTransform.cs:line 105
   at System.Web.Optimization.DependencyCache.<>c__DisplayClassa.<GetFileDependencies>b__4(String s) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:line 72
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Web.Optimization.DependencyCache.GetFileDependencies(Bundle bundle, String virtualPath, BundleContext context) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:line 81
   at System.Web.Optimization.DependencyCache.<>c__DisplayClass1.<GetTransientBundleFilesKey>b__0(BundleFile file) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:line 29
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__81`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Web.Optimization.DependencyCache.ComposeTransientFilesKey(IEnumerable`1 paths) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DependencyCache.cs:line 112
   at System.Web.Optimization.DynamicBundle.GetCacheKey(BundleContext context) in c:\Users\Scott\Documents\GitHub\System.Web.Optimization.Less\System.Web.Optimization.Less\DynamicBundle.cs:line 51
   at System.Web.Optimization.HttpContextCache.Get(BundleContext context, Bundle bundle)
   at System.Web.Optimization.Bundle.CacheLookup(BundleContext context)
   at System.Web.Optimization.Bundle.GetBundleResponse(BundleContext context)
   at System.Web.Optimization.BundleResolver.GetBundleContents(String virtualPath)
   at System.Web.Optimization.AssetManager.EliminateDuplicatesAndResolveUrls(IEnumerable`1 refs)
   at System.Web.Optimization.AssetManager.DeterminePathsToRender(IEnumerable`1 assets)
   at System.Web.Optimization.AssetManager.RenderExplicit(String tagFormat, String[] paths)
   at ASP._Page_Views_Shared___Master_cshtml.Execute() in c:\FtpRoot\www.mywebsite.com\Staging\Views\Shared\__Master.cshtml:line 30
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
   at System.Web.WebPages.WebPageBase.PopContext()
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by scott-xu** [comment]
Please try the latest release.
